const cfg=window.STC_CONFIG||{};
const configured=cfg.SUPABASE_URL?.startsWith('https://')&&!cfg.SUPABASE_ANON_KEY?.startsWith('PASTE_');
const db=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id); let posts=[];
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const slugify=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function showLogin(msg=''){ $('loginView').hidden=false;$('appView').hidden=true;$('loginError').textContent=msg }
function showApp(){ $('loginView').hidden=true;$('appView').hidden=false;showPosts() }
async function boot(){if(!configured)return showLogin('Chưa cấu hình Supabase. Xem file HUONG-DAN-CAI-DAT.md.');const {data:{session}}=await db.auth.getSession();session?showApp():showLogin()}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='Đang đăng nhập...';const {error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});error?showLogin('Email hoặc mật khẩu không đúng.'):showApp()});
$('logout').addEventListener('click',async()=>{await db.auth.signOut();showLogin()});
function switchView(name){$('postsView').hidden=name!=='posts';$('editorView').hidden=name!=='editor';$('pageTitle').textContent=name==='posts'?'Bài viết':($('postId').value?'Chỉnh sửa bài viết':'Viết bài mới');document.querySelectorAll('.nav[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name))}
document.querySelectorAll('.nav[data-view]').forEach(x=>x.addEventListener('click',()=>x.dataset.view==='editor'?newPost():showPosts()));$('newPost').onclick=newPost;$('cancelEdit').onclick=showPosts;
function newPost(){ $('postForm').reset();$('postId').value='';$('publishedAt').value=new Date().toISOString().slice(0,16);$('coverPreview').hidden=true;$('saveMessage').textContent='';switchView('editor') }
$('title').addEventListener('input',()=>{if(!$('postId').value)$('slug').value=slugify($('title').value)});$('coverUrl').addEventListener('input',()=>preview($('coverUrl').value));
function preview(url){$('coverPreview').src=url;$('coverPreview').hidden=!url}
async function loadPosts(){const {data,error}=await db.from('posts').select('*').order('updated_at',{ascending:false});if(error)throw error;posts=data||[];renderPosts()}
function renderPosts(){const q=$('search').value.toLowerCase(),f=$('statusFilter').value,filtered=posts.filter(p=>(f==='all'||p.status===f)&&p.title.toLowerCase().includes(q));$('totalCount').textContent=posts.length;$('publishedCount').textContent=posts.filter(p=>p.status==='published').length;$('draftCount').textContent=posts.filter(p=>p.status==='draft').length;$('postRows').innerHTML=filtered.map(p=>`<tr><td><strong>${escapeHtml(p.title)}</strong><br><small>/${escapeHtml(p.slug)}</small></td><td><span class="status ${p.status}">${p.status==='published'?'Đã xuất bản':'Bản nháp'}</span></td><td>${new Date(p.updated_at).toLocaleDateString('vi-VN')}</td><td><div class="actions"><button data-edit="${p.id}">Sửa</button><button class="danger" data-delete="${p.id}">Xóa</button></div></td></tr>`).join('');$('emptyState').hidden=filtered.length>0;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPost(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deletePost(b.dataset.delete))}
async function showPosts(){switchView('posts');try{await loadPosts()}catch(e){alert('Không tải được bài viết: '+e.message)}}$('search').oninput=renderPosts;$('statusFilter').onchange=renderPosts;
function editPost(id){const p=posts.find(x=>x.id===id);if(!p)return;$('postId').value=p.id;$('title').value=p.title;$('slug').value=p.slug;$('excerpt').value=p.excerpt||'';$('content').value=p.content_html||'';$('status').value=p.status;$('publishedAt').value=p.published_at?new Date(p.published_at).toISOString().slice(0,16):'';$('coverUrl').value=p.cover_url||'';preview(p.cover_url);switchView('editor')}
async function uploadCover(){const file=$('coverFile').files[0];if(!file)return $('coverUrl').value.trim()||null;if(file.size>5*1024*1024)throw new Error('Ảnh phải nhỏ hơn 5 MB.');const ext=file.name.split('.').pop().toLowerCase(),path=`${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('post-images').upload(path,file,{upsert:false});if(error)throw error;return db.storage.from('post-images').getPublicUrl(path).data.publicUrl}
$('postForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('saveMessage').textContent='Đang lưu...';try{const cover=await uploadCover();const status=$('status').value,payload={title:$('title').value.trim(),slug:$('slug').value.trim(),excerpt:$('excerpt').value.trim(),content_html:$('content').value.trim(),cover_url:cover,status,published_at:status==='published'?new Date($('publishedAt').value||Date.now()).toISOString():null};const id=$('postId').value;const query=id?db.from('posts').update(payload).eq('id',id):db.from('posts').insert(payload);const {error}=await query;if(error)throw error;$('saveMessage').textContent='Đã lưu thành công.';setTimeout(showPosts,500)}catch(err){$('saveMessage').textContent='Lỗi: '+err.message}finally{btn.disabled=false}});
async function deletePost(id){const p=posts.find(x=>x.id===id);if(!confirm(`Xóa bài “${p?.title||''}”?`))return;const {error}=await db.from('posts').delete().eq('id',id);if(error)alert('Không thể xóa: '+error.message);else showPosts()}
boot();
