const cfg=window.STC_CONFIG||{},base=cfg.SUPABASE_URL,key=cfg.SUPABASE_ANON_KEY,$=id=>document.getElementById(id);let posts=[];
const sessionKey='stc_admin_session',session=()=>{try{const s=JSON.parse(localStorage.getItem(sessionKey));return s?.access_token?s:null}catch{return null}},esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),slugify=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
async function req(path,{method='GET',body,token,headers={}}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(base+path,{method,body,signal:controller.signal,headers:{apikey:key,Authorization:`Bearer ${token||key}`,...headers}}),text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||`HTTP ${r.status}`);return data}catch(e){if(e.name==='AbortError')throw new Error('Kết nối quá thời gian. Vui lòng thử lại.');throw e}finally{clearTimeout(timer)}}
function showLogin(msg=''){$('loginView').hidden=false;$('appView').hidden=true;$('loginError').textContent=msg}function showApp(){$('loginView').hidden=true;$('appView').hidden=false;showPosts()}
function boot(){if(!base?.startsWith('https://')||key?.startsWith('PASTE_'))return showLogin('Chưa cấu hình Supabase.');session()?showApp():showLogin()}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;$('loginError').textContent='Đang đăng nhập...';try{const data=await req('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value}),headers:{'Content-Type':'application/json'}});localStorage.setItem(sessionKey,JSON.stringify(data));showApp()}catch(err){showLogin('Không đăng nhập được: '+err.message)}finally{b.disabled=false}});$('logout').onclick=()=>{localStorage.removeItem(sessionKey);showLogin()};
function switchView(n){$('postsView').hidden=n!=='posts';$('editorView').hidden=n!=='editor';$('pageTitle').textContent=n==='posts'?'Bài viết':($('postId').value?'Chỉnh sửa bài viết':'Viết bài mới');document.querySelectorAll('.nav[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===n))}function newPost(){$('postForm').reset();$('postId').value='';$('publishedAt').value=new Date().toISOString().slice(0,16);$('coverPreview').hidden=true;$('saveMessage').textContent='';switchView('editor')}
document.querySelectorAll('.nav[data-view]').forEach(x=>x.onclick=()=>x.dataset.view==='editor'?newPost():showPosts());$('newPost').onclick=newPost;$('cancelEdit').onclick=showPosts;$('title').oninput=()=>{if(!$('postId').value)$('slug').value=slugify($('title').value)};$('coverUrl').oninput=()=>preview($('coverUrl').value);function preview(url){$('coverPreview').src=url||'';$('coverPreview').hidden=!url}
async function loadPosts(){posts=await req('/rest/v1/posts?select=*&order=updated_at.desc',{token:session().access_token})||[];renderPosts()}function renderPosts(){const q=$('search').value.toLowerCase(),f=$('statusFilter').value,a=posts.filter(p=>(f==='all'||p.status===f)&&p.title.toLowerCase().includes(q));$('totalCount').textContent=posts.length;$('publishedCount').textContent=posts.filter(p=>p.status==='published').length;$('draftCount').textContent=posts.filter(p=>p.status==='draft').length;$('postRows').innerHTML=a.map(p=>`<tr><td><strong>${esc(p.title)}</strong><br><small>/${esc(p.slug)}</small></td><td><span class="status ${p.status}">${p.status==='published'?'Đã xuất bản':'Bản nháp'}</span></td><td>${new Date(p.updated_at).toLocaleDateString('vi-VN')}</td><td><div class="actions"><button data-edit="${p.id}">Sửa</button><button class="danger" data-delete="${p.id}">Xóa</button></div></td></tr>`).join('');$('emptyState').hidden=!!a.length;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPost(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deletePost(b.dataset.delete))}
async function showPosts(){switchView('posts');try{await loadPosts()}catch(e){if(/JWT|token|401/i.test(e.message)){localStorage.removeItem(sessionKey);showLogin('Phiên đăng nhập hết hạn.')}else alert('Không tải được bài viết: '+e.message)}}$('search').oninput=renderPosts;$('statusFilter').onchange=renderPosts;
function editPost(id){const p=posts.find(x=>x.id===id);if(!p)return;$('postId').value=p.id;$('title').value=p.title;$('slug').value=p.slug;$('excerpt').value=p.excerpt||'';$('content').value=p.content_html||'';$('status').value=p.status;$('publishedAt').value=p.published_at?new Date(p.published_at).toISOString().slice(0,16):'';$('coverUrl').value=p.cover_url||'';preview(p.cover_url);switchView('editor')}
async function uploadCover(){const f=$('coverFile').files[0];if(!f)return $('coverUrl').value.trim()||null;if(f.size>5242880)throw new Error('Ảnh phải nhỏ hơn 5 MB.');const path=`${Date.now()}-${crypto.randomUUID()}.${f.name.split('.').pop().toLowerCase()}`;await req(`/storage/v1/object/post-images/${path}`,{method:'POST',body:f,token:session().access_token,headers:{'Content-Type':f.type,'x-upsert':'false'}});return `${base}/storage/v1/object/public/post-images/${path}`}
$('postForm').addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;$('saveMessage').textContent='Đang lưu...';try{const status=$('status').value,p={title:$('title').value.trim(),slug:$('slug').value.trim(),excerpt:$('excerpt').value.trim(),content_html:$('content').value.trim(),cover_url:await uploadCover(),status,published_at:status==='published'?new Date($('publishedAt').value||Date.now()).toISOString():null},id=$('postId').value;await req(id?`/rest/v1/posts?id=eq.${encodeURIComponent(id)}`:'/rest/v1/posts',{method:id?'PATCH':'POST',body:JSON.stringify(p),token:session().access_token,headers:{'Content-Type':'application/json','Prefer':'return=minimal'}});$('saveMessage').textContent='Đã lưu thành công.';setTimeout(showPosts,500)}catch(err){$('saveMessage').textContent='Lỗi: '+err.message}finally{b.disabled=false}});async function deletePost(id){const p=posts.find(x=>x.id===id);if(!confirm(`Xóa bài “${p?.title||''}”?`))return;try{await req(`/rest/v1/posts?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',token:session().access_token});showPosts()}catch(e){alert('Không thể xóa: '+e.message)}}boot();
